export const {
  VITE_COINFLIP_NATIVE_PROGRAM: COINFLIP_NATIVE_PROGRAM,
  VITE_COINFLIP_TOKEN_PROGRAM: COINFLIP_TOKEN_PROGRAM,
  VITE_ALEO_BASE_URL,
  VITE_NETWORK_TYPE,
  VITE_LOOT_TOKEN_MINT_PROGRAM,
  VITE_LOTTERY_PROGRAM
} = import.meta.env;
